Move Go code into tool directory. (#2)

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -12,26 +12,26 @@ for f in $new_files; do
   if ! grep -l "Copyright .* Toitware" "$f" 2>&1 1>/dev/null; then
     missing_copyright="$f $missing_copyright"
   else
-    if ! grep -l "governed.*MIT" "$f"  2>&1 1>/dev/null; then
-      missing_mit="$f $missing_mit"
+    if ! grep -l "governed.*\(MIT\|BSD\)" "$f"  2>&1 1>/dev/null; then
+      missing_governed="$f $missing_governed"
     fi
   fi
 done
 
-if [ -n "$missing_copyright" ]; then
+if [[ -n "$missing_copyright" ]]; then
   echo "Missing copyright in:"
   for f in $missing_copyright; do
     echo "  $f"
   done
 fi
 
-if [ -n "$missing_mit" ]; then
-  echo "Missing MIT line:"
-  for f in $missing_mit; do
+if [[ -n "$missing_governed" ]]; then
+  echo "Missing governed line:"
+  for f in $missing_governed; do
     echo "  $f"
   done
 fi
 
-if [ -n "$missing_copyright" ] || [ -n "$missing_mit" ]; then
+if [ -n "$missing_copyright" ] || [ -n "$missing_governed" ]; then
   exit 1;
 fi
